### ISSUE TITLE
Створити скрипт для генерації бази даних. Створити ER діаграму

### ISSUE THREAD

**Issue by horbaldaniil** [horbaldaniil/SecurePass#11]

**Comment by YaremaTymchyshyn** [comment]
https://lucid.app/lucidchart/d7a369cd-1b53-4d12-92f0-9765ffa28277/edit?viewport_loc=-638%2C-459%2C2544%2C1304%2C0_0&invitationId=inv_3b58c44a-029c-42c6-9b4e-ad8658e9c066
